/*
 * Initialize Spell Types -- Do not forget to add new spells to here.
 * Written for Asgardian NightMare by Skyntil(Gabe Volker) 4/20/00
 * This File Can be Generated on Bootup If so Desired.
 * It could be also done online. This would avoid having to add
 * new spells manually.
 */
#include "include.h"

#define SPELL_TYPE(name,type) magic_table[skill_lookup(name)] = type;
#define IS_SPELL_WHITE(sn) (magic_table[sn] == MAGIC_WHITE) ? TRUE : FALSE
#define IS_SPELL_RED(sn) (magic_table[sn] == MAGIC_RED) ? TRUE : FALSE
#define IS_SPELL_BLUE(sn) (magic_table[sn] == MAGIC_BLUE) ? TRUE : FALSE
#define IS_SPELL_BLACK(sn) (magic_table[sn] == MAGIC_BLACK) ? TRUE : FALSE
#define IS_SPELL_GREEN(sn) (magic_table[sn] == MAGIC_GREEN) ? TRUE : FALSE
#define IS_SPELL_ORANGE(sn) (magic_table[sn] == MAGIC_ORANGE) ? TRUE : FALSE
/*
#define MAGIC_NONE  -1
#define MAGIC_WHITE  0   // Healing/Protection
#define MAGIC_RED    1   // Combat
#define MAGIC_BLUE   2   // Detection/Transportation/Creation
#define MAGIC_GREEN  3   // Enhance/Enchant
#define MAGIC_BLACK  4   // Evil--Take a guess
#define MAGIC_ORANGE 5   // Illusion/Benediction/Miscellaneous
*/

void initialize_spell_types( )
{
 log_string( "Initializing Magic Types." );

SPELL_TYPE( "acetum primus", MAGIC_RED )
SPELL_TYPE( "achilles", MAGIC_GREEN )
SPELL_TYPE( "acid arrow", MAGIC_RED )
SPELL_TYPE( "acid blast", MAGIC_RED )
SPELL_TYPE( "acid breath", MAGIC_RED )
// SPELL_TYPE( "acid rain", MAGIC_RED )
SPELL_TYPE( "acute vision", MAGIC_BLUE )
SPELL_TYPE( "adamantite golem", MAGIC_BLUE )
SPELL_TYPE( "aid", MAGIC_GREEN )
SPELL_TYPE( "animal instinct", MAGIC_GREEN )
SPELL_TYPE( "animate dead", MAGIC_BLACK )
SPELL_TYPE( "armor", MAGIC_WHITE )
SPELL_TYPE( "assist", MAGIC_WHITE )
SPELL_TYPE( "astral walk", MAGIC_BLUE )
// SPELL_TYPE( "barrier", MAGIC_WHITE )
SPELL_TYPE( "bless", MAGIC_ORANGE )
SPELL_TYPE( "bark skin", MAGIC_WHITE );
SPELL_TYPE( "blindness", MAGIC_BLACK )
SPELL_TYPE( "burning hands", MAGIC_RED )
SPELL_TYPE( "call lightning", MAGIC_RED )
SPELL_TYPE( "calm", MAGIC_WHITE )
SPELL_TYPE( "cancellation", MAGIC_BLUE )
SPELL_TYPE( "cause critical", MAGIC_RED )
SPELL_TYPE( "cause light", MAGIC_RED )
SPELL_TYPE( "cause serious", MAGIC_RED )
SPELL_TYPE( "caustic font", MAGIC_RED )
SPELL_TYPE( "chain lightning", MAGIC_RED )
SPELL_TYPE( "change sex", MAGIC_ORANGE )
SPELL_TYPE( "channel", MAGIC_ORANGE )
SPELL_TYPE( "charm person", MAGIC_ORANGE )
SPELL_TYPE( "chill touch", MAGIC_BLACK )
SPELL_TYPE( "cocoon", MAGIC_WHITE )
SPELL_TYPE( "colour spray", MAGIC_RED )
// SPELL_TYPE( "conjure", MAGIC_BLUE )
SPELL_TYPE( "continual light", MAGIC_BLUE )
SPELL_TYPE( "control weather", MAGIC_ORANGE )
// SPELL_TYPE( "conjure blizzard", MAGIC_RED )
// SPELL_TYPE( "courage", MAGIC_WHITE )
SPELL_TYPE( "create food", MAGIC_BLUE )
SPELL_TYPE( "create rose", MAGIC_BLUE )
SPELL_TYPE( "create spring", MAGIC_BLUE )
SPELL_TYPE( "create water", MAGIC_BLUE )
SPELL_TYPE( "cure blindness", MAGIC_WHITE )
SPELL_TYPE( "cure critical", MAGIC_WHITE )
SPELL_TYPE( "cure disease", MAGIC_WHITE )
SPELL_TYPE( "cure light", MAGIC_WHITE )
SPELL_TYPE( "cure poison", MAGIC_WHITE )
SPELL_TYPE( "cure serious", MAGIC_WHITE )
SPELL_TYPE( "curse", MAGIC_BLACK )
// SPELL_TYPE( "deathshield", MAGIC_BLACK )
SPELL_TYPE( "death ray", MAGIC_BLACK )
SPELL_TYPE( "demonfire", MAGIC_BLACK )
SPELL_TYPE( "desert fist", MAGIC_RED )
// SPELL_TYPE( "betray", MAGIC_BLACK )
SPELL_TYPE( "detect evil", MAGIC_BLUE )
SPELL_TYPE( "detect good", MAGIC_BLUE )
// SPELL_TYPE( "detect motion", MAGIC_BLUE )
SPELL_TYPE( "detect hidden", MAGIC_BLUE )
SPELL_TYPE( "detect invis", MAGIC_BLUE )
// SPELL_TYPE( "detect location", MAGIC_BLUE )
SPELL_TYPE( "detect magic", MAGIC_RED )
SPELL_TYPE( "detect poison", MAGIC_BLUE )
SPELL_TYPE( "dispel evil", MAGIC_RED )
SPELL_TYPE( "dispel good", MAGIC_BLACK )
// SPELL_TYPE( "dispel invis", MAGIC_GREEN )
SPELL_TYPE( "dispel magic", MAGIC_RED )
SPELL_TYPE( "disruption", MAGIC_RED )
// SPELL_TYPE( "displace", MAGIC_WHITE )
SPELL_TYPE( "doppelganger", MAGIC_BLUE )
SPELL_TYPE( "earthquake", MAGIC_RED )
// SPELL_TYPE( "empower", MAGIC_BLUE )
SPELL_TYPE( "enchant armor", MAGIC_GREEN )
SPELL_TYPE( "enchant weapon", MAGIC_GREEN )
SPELL_TYPE( "energy drain", MAGIC_BLACK )
// SPELL_TYPE( "entity", MAGIC_RED )
SPELL_TYPE( "etheral fist", MAGIC_RED )
SPELL_TYPE( "faerie fire", MAGIC_GREEN )
SPELL_TYPE( "faerie fog", MAGIC_BLUE )
SPELL_TYPE( "farsight", MAGIC_BLUE )
// SPELL_TYPE( "feeble mind", MAGIC_GREEN )
SPELL_TYPE( "fireball", MAGIC_RED )
SPELL_TYPE( "fire breath", MAGIC_RED )
SPELL_TYPE( "fireproof", MAGIC_ORANGE )
SPELL_TYPE( "fireshield", MAGIC_WHITE )
SPELL_TYPE( "flame shield", MAGIC_GREEN )
SPELL_TYPE( "flamestrike", MAGIC_RED )
// SPELL_TYPE( "floating disc", MAGIC_BLUE )
SPELL_TYPE( "fly", MAGIC_ORANGE )
SPELL_TYPE( "force shield", MAGIC_GREEN )
SPELL_TYPE( "frenzy", MAGIC_ORANGE )
SPELL_TYPE( "frost breath", MAGIC_RED )
// SPELL_TYPE( "generations", MAGIC_BLUE )
// SPELL_TYPE( "fireward", MAGIC_RED )
// SPELL_TYPE( "iceward", MAGIC_BLUE )
// SPELL_TYPE( "acidward", MAGIC_WHITE )
// SPELL_TYPE( "interven", MAGIC_WHITE )
// SPELL_TYPE( "madness", MAGIC_ORANGE )
SPELL_TYPE( "galvanic whip", MAGIC_RED )
SPELL_TYPE( "gas breath", MAGIC_RED )
 SPELL_TYPE( "gate", MAGIC_BLUE )
SPELL_TYPE( "giant strength", MAGIC_BLUE )
SPELL_TYPE( "godsword", MAGIC_BLUE )
SPELL_TYPE( "hand of undead", MAGIC_BLACK )
SPELL_TYPE( "harm", MAGIC_RED )
SPELL_TYPE( "haste", MAGIC_GREEN )
SPELL_TYPE( "heal", MAGIC_WHITE )
SPELL_TYPE( "heat metal", MAGIC_GREEN )
SPELL_TYPE( "holy word", MAGIC_RED )
// SPELL_TYPE( "iceshield", MAGIC_WHITE )
SPELL_TYPE( "identify", MAGIC_BLUE )
SPELL_TYPE( "infravision", MAGIC_BLUE )
SPELL_TYPE( "improved heal", MAGIC_WHITE )
SPELL_TYPE( "invisibility", MAGIC_ORANGE )
SPELL_TYPE( "investiture", MAGIC_ORANGE )
SPELL_TYPE( "knights shield", MAGIC_BLUE )
SPELL_TYPE( "know alignment", MAGIC_ORANGE )
SPELL_TYPE( "lightning bolt", MAGIC_RED )
SPELL_TYPE( "locate object", MAGIC_BLUE )
SPELL_TYPE( "magic missile", MAGIC_RED )
SPELL_TYPE( "magnetic trust", MAGIC_ORANGE )
// SPELL_TYPE( "mana blast", 	MAGIC_RED  )
// SPELL_TYPE( "martyr",		MAGIC_WHITE )
SPELL_TYPE( "mass healing", MAGIC_WHITE )
SPELL_TYPE( "mass invis", MAGIC_ORANGE )
SPELL_TYPE( "mental knife", MAGIC_RED )
SPELL_TYPE( "mind wrack", MAGIC_RED )
SPELL_TYPE( "mind wrench", MAGIC_RED )
SPELL_TYPE( "nexus", MAGIC_BLUE )
// SPELL_TYPE( "quench", MAGIC_WHITE )
// SPELL_TYPE( "sate", MAGIC_WHITE )
SPELL_TYPE( "pass door", MAGIC_ORANGE )
SPELL_TYPE( "plague", MAGIC_BLACK )
SPELL_TYPE( "poison", MAGIC_BLACK )
SPELL_TYPE( "portal", MAGIC_BLUE )
SPELL_TYPE( "powerstorm", MAGIC_RED )
SPELL_TYPE( "power word kill", MAGIC_BLACK )
SPELL_TYPE( "power word stun", MAGIC_BLACK )
// SPELL_TYPE( "prismatic spray", MAGIC_RED )
SPELL_TYPE( "protection evil", MAGIC_WHITE )
SPELL_TYPE( "protection good", MAGIC_WHITE )
// SPELL_TYPE( "protection voodoo", MAGIC_WHITE )
SPELL_TYPE( "protection negative", MAGIC_WHITE )
// SPELL_TYPE( "quest pill", MAGIC_NONE )
SPELL_TYPE( "quantum spike", MAGIC_RED )
SPELL_TYPE( "rabies", MAGIC_GREEN )
SPELL_TYPE( "ray of truth", MAGIC_RED )
SPELL_TYPE( "recharge", MAGIC_GREEN )
SPELL_TYPE( "refresh", MAGIC_WHITE )
SPELL_TYPE( "repair", MAGIC_ORANGE )
SPELL_TYPE( "remove curse", MAGIC_WHITE )
// SPELL_TYPE( "restore mana", MAGIC_WHITE )
// SPELL_TYPE( "resurrect", MAGIC_WHITE )
SPELL_TYPE( "sacred cloak", MAGIC_WHITE )
SPELL_TYPE( "sanctuary", MAGIC_WHITE )
SPELL_TYPE( "scourge", MAGIC_BLACK )
SPELL_TYPE( "shield", MAGIC_WHITE )
SPELL_TYPE( "shocking grasp", MAGIC_RED )
SPELL_TYPE( "shockshield", MAGIC_WHITE )
SPELL_TYPE( "siphon life", MAGIC_GREEN )
SPELL_TYPE( "siphon energy", MAGIC_GREEN )
SPELL_TYPE( "sleep", MAGIC_GREEN )
SPELL_TYPE( "slow", MAGIC_GREEN )
SPELL_TYPE( "sonic resonance", MAGIC_RED )
SPELL_TYPE( "spectral furor", MAGIC_RED )
SPELL_TYPE( "static shield", MAGIC_WHITE )
SPELL_TYPE( "stone skin", MAGIC_WHITE )
SPELL_TYPE( "sulfurus spray", MAGIC_RED )
// SPELL_TYPE( "holy aura",  MAGIC_WHITE )
// SPELL_TYPE( "summon", MAGIC_BLUE )
SPELL_TYPE( "teleport", MAGIC_BLUE )
// SPELL_TYPE( "torrents of flame", MAGIC_RED )
// SPELL_TYPE( "transport", MAGIC_BLUE )
// SPELL_TYPE( "unite", MAGIC_RED )
SPELL_TYPE( "tesseract", MAGIC_BLUE )
SPELL_TYPE( "ventriloquate", MAGIC_ORANGE )
// SPELL_TYPE( "voodoo", MAGIC_BLACK )
SPELL_TYPE( "weaken", MAGIC_BLACK )
SPELL_TYPE( "web", MAGIC_RED )
// SPELL_TYPE( "wizard eye", MAGIC_BLUE )
SPELL_TYPE( "word of recall", MAGIC_BLUE )
SPELL_TYPE( "wrath of god", MAGIC_WHITE )
SPELL_TYPE( "general purpose", MAGIC_RED )
SPELL_TYPE( "high explosive", MAGIC_RED )

/*
SPELL_TYPE( "acid breath", MAGIC_RED )
SPELL_TYPE( "fire breath", MAGIC_RED )
SPELL_TYPE( "frost breath", MAGIC_RED )
SPELL_TYPE( "gas breath", MAGIC_RED )
SPELL_TYPE( "lightning breath", MAGIC_RED )
SPELL_TYPE( "stomp", MAGIC_RED )
SPELL_TYPE( "divine intervention", MAGIC_WHITE)
SPELL_TYPE( "divine protection", MAGIC_WHITE )
SPELL_TYPE( "protective aura", MAGIC_WHITE )
SPELL_TYPE( "turn undead", MAGIC_RED )
SPELL_TYPE( "constance", MAGIC_ORANGE )
SPELL_TYPE( "wrath of god", MAGIC_RED )
SPELL_TYPE( "forestwalk", MAGIC_BLUE )
SPELL_TYPE( "shadowgate", MAGIC_BLUE )
SPELL_TYPE( "crevice", MAGIC_RED )
SPELL_TYPE( "entangle", MAGIC_GREEN )
SPELL_TYPE( "charm song", MAGIC_ORANGE )
SPELL_TYPE( "calming song", MAGIC_ORANGE )
SPELL_TYPE( "sonic blast", MAGIC_RED )
SPELL_TYPE( "rage", MAGIC_RED )
SPELL_TYPE( "conjure wrath", MAGIC_RED )
SPELL_TYPE( "channel", MAGIC_WHITE )
SPELL_TYPE( "wither", MAGIC_BLACK )
SPELL_TYPE( "soulbind", MAGIC_ORANGE )
SPELL_TYPE( "domineer", MAGIC_RED )
SPELL_TYPE( "earthmeld", MAGIC_ORANGE )
SPELL_TYPE( "headache", MAGIC_RED )
SPELL_TYPE( "dimension walk", MAGIC_BLUE )
SPELL_TYPE( "animate dead", MAGIC_BLACK )
SPELL_TYPE( "animate skeleton", MAGIC_BLACK )
SPELL_TYPE( "mummify", MAGIC_BLACK )
SPELL_TYPE( "decay corpse", MAGIC_BLACK )
SPELL_TYPE( "globe of invulnerability", MAGIC_WHITE)
SPELL_TYPE( "steel flesh", MAGIC_WHITE)
SPELL_TYPE( "mana shield", MAGIC_WHITE)
SPELL_TYPE( "darkshield", MAGIC_BLACK)
SPELL_TYPE( "illusionary armor", MAGIC_WHITE)
SPELL_TYPE( "darken blade", MAGIC_BLACK)
SPELL_TYPE( "empower blade", MAGIC_BLUE)
SPELL_TYPE( "flame blade", MAGIC_RED)
SPELL_TYPE( "frost blade", MAGIC_WHITE)
SPELL_TYPE( "acid blade", MAGIC_GREEN)
SPELL_TYPE( "transmute", MAGIC_GREEN)
SPELL_TYPE( "lesser golem", MAGIC_BLACK)
SPELL_TYPE( "greater golem", MAGIC_BLACK)
SPELL_TYPE( "preserve limb", MAGIC_BLACK)
SPELL_TYPE( "cremate", MAGIC_BLACK)
SPELL_TYPE( "fear", MAGIC_BLACK)
SPELL_TYPE( "imbue weapon", MAGIC_WHITE)
SPELL_TYPE( "restore", MAGIC_WHITE)
SPELL_TYPE( "voodan curse", MAGIC_BLACK)
SPELL_TYPE( "soul burn", MAGIC_BLACK)
SPELL_TYPE( "sense vitality", MAGIC_BLACK)
SPELL_TYPE( "fortify strength", MAGIC_WHITE)
SPELL_TYPE( "fortify intelligence", MAGIC_WHITE)
SPELL_TYPE( "fortify dexterity", MAGIC_WHITE)
SPELL_TYPE( "fortify wisdom", MAGIC_WHITE)
SPELL_TYPE( "fortify constitution", MAGIC_WHITE)
SPELL_TYPE( "flesh golem", MAGIC_BLACK)
SPELL_TYPE( "iron golem", MAGIC_BLACK)
SPELL_TYPE( "overgrowth", MAGIC_BLUE)
SPELL_TYPE( "fork", MAGIC_RED)
SPELL_TYPE( "insomnia", MAGIC_BLACK)
*/
return;
}
