#! /bin/csh -f

set port = 2850
if ( "$1" != "" ) set port="$1"

nice
limit coredumpsize 8128k
limit filesize 16256k
if ( -e ../txt/shutdown.txt ) rm -f ../txt/shutdown.txt

while ( 1 )
     set index = 1000
     while ( 1 )
 	set logfile = ../log/$index.log
 	if ( ! -e $logfile ) break
 	@ index++
     end

    cd ../area
    ../src/rom $port >&! $logfile

    if ( -e ../txt/shutdown.txt ) then
	rm -f ../txt/shutdown.txt
	exit 0
    endif
    sleep 2
end
